FROM nodered/node-red-docker

MAINTAINER Justin Phillips "jphillips@bp-3.com"

RUN npm install @bp3/node-red-contrib-ibm-odm-make-decision

# This build does not need a start command for Node-RED because this is done by the base image (see FROM)
